apiVersion: v1
kind: Service
metadata:
  name: react-k8s-app-loadbalancer-service
  labels:
    app: react-k8s-app
spec:
  selector:
    app: react-k8s-app
    ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    type: LoadBalancer